import Option from "../compoment/Option";

export default function () {
    return (
        <div className="w-11/12 md:w-9/12 m-auto h-auto py-20 ">
            <h2 className=" text-4xl my-10 text-center md:text-7xl">Dans quel domaine souhaitez-vous <br /> vous former ?</h2>
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('https://course.oc-static.com/courses/1946116/1946116_teaser_picture_1680855988.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/1946116-avoir-laudace-dentreprendre#/id/video_Player_1" description="Vous pensez que l’entrepreneuriat n’est pas pour vous ? Qu’il faut obligatoirement de grandes idées ? Que seuls de grands noms comme Bill Gates, Steve Jobs, etc. sont des entrepreneurs ? Notre cours a pour objectif de rompre avec ces idées reçues et vous montrer que vous pouvez vous aussi devenir entrepreneur. Quel est son quotidien ? Quelles sont ses qualités ? Comment les acquérir ? Comment mettre en place son projet ? Tout au long de ce cours, nous allons vous faire découvrir la réalité qui se cache derrière ce mot à la mode et vous proposer tous les outils pour vous aider à identifier comme tel."  />
            <Option title="Maîtrisez les fondamentaux d'Excel" classe="bg-[url('https://course.oc-static.com/courses/7168336/7168336_teaser_picture_1680858737.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/7168336-maitrisez-les-fondamentaux-dexcel#/id/video_Player_1" description="Le logiciel Excel fait partie des logiciels les plus utilisés dans le monde. Tous ceux qui s'en servent au quotidien savent que ce n'est pas sans raison ! Excel vous permet facilement de traiter de nombreuses données et de les mettre en forme.Ce cours vous permettra de prendre en main ce logiciel si vous êtes débutant, de mettre en page vos données pour qu'elles soient facilement lisibles, et de les manipuler grâce aux formules, aux fonctionnalités de tri, aux tableaux croisés dynamiques, etc. Il vous permettra également de vous préparer à la certification TOSA Excel niveau basique." />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('https://course.oc-static.com/courses/7168336/7168336_teaser_picture_1680858737.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/7168336-maitrisez-les-fondamentaux-dexcel#/id/video_Player_1" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('client/src/assets/pexels-rocketmann-team-9486890.jpg')]" action='Commencer la formation' link="" description="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Perspiciatis, a at, illo assumenda adipisci accusamus eligendi iste quo deserunt deleniti aliquid cum dignissimos dolor. Repudiandae assumenda cum maxime atque! Unde?" />
            <button className="flex text-[#3563FF] hover:text-[#FFC801]">
                <h3 className="border-b-2 border-[#3563FF] hover:border-[#FFC801] text-2xl ">Decouvrir plus de formation sur Open Classroom</h3>
                {/* <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" className="w-20 h-10 self-center fill-black pt-2"><path d="M438.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-160-160c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L338.8 224 32 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l306.7 0L233.4 393.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l160-160z" /></svg> */}
            </button>
        </div>
    )
}