import Option from "../compoment/Option";

export default function () {
    return (
        <div className="w-11/12 md:w-9/12 m-auto h-auto py-20 ">
            <h2 className=" text-4xl my-10 text-center md:text-7xl">Dans quel domaine souhaitez-vous <br /> vous former ?</h2>
            <Option title="Avoir l'audace d'entreprendre" classe="bg-[url('https://course.oc-static.com/courses/1946116/1946116_teaser_picture_1680855988.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/1946116-avoir-laudace-dentreprendre#/id/video_Player_1" description="Vous pensez que l’entrepreneuriat n’est pas pour vous ? Qu’il faut obligatoirement de grandes idées ? Que seuls de grands noms comme Bill Gates, Steve Jobs, etc. sont des entrepreneurs ? Notre cours a pour objectif de rompre avec ces idées reçues et vous montrer que vous pouvez vous aussi devenir entrepreneur. Quel est son quotidien ? Quelles sont ses qualités ? Comment les acquérir ? Comment mettre en place son projet ? Tout au long de ce cours, nous allons vous faire découvrir la réalité qui se cache derrière ce mot à la mode et vous proposer tous les outils pour vous aider à identifier comme tel." />
            <Option title="Développez votre réseau professionnel" classe="bg-[url('https://www.codeur.com/blog/wp-content/uploads/2016/09/ressources-creer-reseau-social-740x368.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/5754261-developpez-votre-reseau-professionnel#/id/video_Player_1" description="Notre monde s’accélère, les distances se raccourcissent, les réseaux sociaux se développent et l’usage des applications mobiles nous permet d’être toujours connectés et disponibles. Bien exploité, cela constitue de véritables opportunités, que vous allez ici apprendre à cultiver. Dans ce cours, vous découvrirez tout ce que le networking a à vous offrir. Vous apprendrez comment développer votre réseau, comment utiliser les médias sociaux pour approcher les bonnes personnes de manière stratégique et comment entretenir ce réseau dans le temps." />
            <Option title="Business Intelligence Analyst" classe="bg-[url('client/src/assets/formation0001.png')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/7168336-maitrisez-les-fondamentaux-dexcel#/id/video_Player_1" description="Désormais incontournable dans de nombreux secteurs, la Business Intelligence (ou “informatique décisionnelle” en français), regroupe une variété d’outils et de méthodes ayant pour but de rendre l’information plus accessible et compréhensible à tous les collaborateurs susceptibles d’en tirer bénéfice. Le Business Intelligence Analyst, aussi appelé Data Analyst BI, a pour rôle de faciliter la prise de décisions stratégiques et commerciales en collectant, en analysant et en synthétisant des données variées." />
            <Option title="Maîtrisez les fondamentaux d'Excel" classe="bg-[url('https://course.oc-static.com/courses/7168336/7168336_teaser_picture_1680858737.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/7168336-maitrisez-les-fondamentaux-dexcel#/id/video_Player_1" description="Le logiciel Excel fait partie des logiciels les plus utilisés dans le monde. Tous ceux qui s'en servent au quotidien savent que ce n'est pas sans raison ! Excel vous permet facilement de traiter de nombreuses données et de les mettre en forme.Ce cours vous permettra de prendre en main ce logiciel si vous êtes débutant, de mettre en page vos données pour qu'elles soient facilement lisibles, et de les manipuler grâce aux formules, aux fonctionnalités de tri, aux tableaux croisés dynamiques, etc. Il vous permettra également de vous préparer à la certification TOSA Excel niveau basique." />
            <Option title="Chef de projet marketing" classe="bg-[url('https://greenloop.eu/wp-content/uploads/2021/10/Greenloop-formations-petit.svg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses" description="À la suite de cette formation diplômante, vous pourrez exercer de nombreux métiers dont celui de chef de projet marketing, mais également ceux de responsable marketing digital, responsable marketing opérationnel, responsable communication, online acquisition manager, account manager, community manager, etc." />
            <Option title="Utilisez ChatGPT pour améliorer votre productivité" classe="bg-[url('https://www.alcimia.com/wp-content/uploads/2023/02/chat-gpt-qui-quoi-comment.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/8204091-utilisez-chatgpt-pour-ameliorer-votre-productivite#/id/video_Player_1" description="L'IA (Intelligence Artificielle) est soudainement devenue concrète.Alors, que peut-on faire avec cette IA aujourd'hui ? Comment peut-elle vous faire gagner du temps dans votre quotidien, et en particulier au travail ? Dans ce cours, je vais vous montrer comment faire vos premiers pas avec ChatGPT et ensuite, comment vous pouvez utiliser ChatGPT pour, par exemple :Générer du texte ;Créer des résumés ; Traduire dans n'importe quelle langue ; Brainstormer des idées ;... Et même créer un plan pour mieux vous organiser dans votre travail !" />
            <Option title="Obtenez l'emploi qui vous correspond" classe="bg-[url('https://cdn.makemycv.fr/images/conseils-recherche-emploi.jpg')]" action='Commencer la formation' link="https://openclassrooms.com/fr/courses/5218241-obtenez-lemploi-qui-vous-correspond#/id/video_Player_1" description="Vous avez repéré le job de vos rêves ? Voici venu le moment de postuler, de vous présenter directement aux recruteurs et de vous rendre incontournable. Dans ce cours, vous verrez comment mettre toutes les chances de votre côté en envoyant une lettre de motivation ciblée et ainsi décrocher un entretien. Nous vous donnerons ensuite les clés pour un entretien d'embauche réussi afin de passer cette dernière étape. Si vous souhaitez obtenir l'emploi qui vous correspond, rendez-vous au premier chapitre !" />
            <a href="https://openclassrooms.com/" target="_blank" rel="noopener noreferrer" className="text-[#3563FF] hover:text-[#385A64] text-center border-b-2 border-[#3563FF] hover:border-[#385A64] text-xl ">Decouvrir plus de formation sur Open Classroom</a>
        </div>
    )
}